services:
  - type: web
    name: mailbox-proxy-server
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn user_server:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.9.0